### ISSUE TITLE
custom telemeter integration

### ISSUE THREAD

**Issue by myTselection** [bramvandenbussche/ha-telemeter#1]
hi, just FYI, some time ago I've build a custom integration that can retrieve all telenet telemeter data (for old and new Telenet backend).
People looking at your code might also be interested into it, as it's easy to install using HACS. Feel free to link: https://github.com/myTselection/telenet_telemeter

**Comment by bramvandenbussche** [comment]
Hi! I'm happy to do so. Telenet recently updated their API and now this integration doesn't work anymore, because the underlying library hasn't been updated. I've actually switched to your HA integration instead and am loving it. Thanks for this!
